#!/bin/bash
../tools/steps/step-mono -FLATSTART -NUMMIXES 20  ../convert/fbk25d/env/environment_Z \ FBK_Z_Flatstart20/mono
../tools/steps/step-mono -NUMMIXES 20  ../convert/fbk25d/env/environment_Z \ FBK_Z_Init20/mono

#Training with filter bank with different env / parametisations
for deltaparam in E_D_Z E_D_A_Z E_Z
do
../tools/steps/step-mono -FLATSTART -NUMMIXES 20  ../convert/mfc13d/env/environment${deltaparam} \ FBK${deltaparam}_Flatstart20/mono
../tools/steps/step-mono -NUMMIXES 20  ../convert/mfc13d/env/environment${deltaparam} \ FBK${deltaparam}_Init20/mono
done
#Training with MFCC with different env / parametisations
for deltaparam in _D_Z _D_A_Z 
do
../tools/steps/step-mono -FLATSTART -NUMMIXES 20  ../convert/fbk25d/env/environment${deltaparam} \ FBK${deltaparam}_Flatstart20/mono
../tools/steps/step-mono -NUMMIXES 20  ../convert/fbk25d/env/environment${deltaparam} \ FBK${deltaparam}_Init20/mono
done

#Decoding without options
do 
for file in FBK_Z_Init20 FBK_D_Z_Init20 FBK_D_A_Z_Init20 FBK_D_A_Z_Flatstart20 FBK_D_Z_Flatstart20 MFC_Z_Init20 MFC_D_Z_Init20 MFC_D_A_Z_Init20 MFC_D_A_Z_Flatstart20 MFC_D_Z_Flatstart20 MFC_Z_Flatstart20
	do
	for i in $(seq 2 2 20)
	do
	hmm=hmm${i}4
	filename=decode-mono-$hmm
	../tools/steps/step-decode $PWD/$file/mono $hmm $file/NOOPTIONS/$filename
	echo $file $filename no option >>text.txt
	grep -A2 -P 'SENT' $file/NOOPTION/$filename/test/LOG >>text.txt
	done
done

#Decoding without options - Missing:Pruning with BEAMWIDTH
for option in CORETEST SUBTRAIN INSWORD GRAMMARSCALE
  do 
    for file in FBK_Z_Init20 FBK_D_Z_Init20 FBK_D_A_Z_Init20 FBK_D_A_Z_Flatstart20 FBK_D_Z_Flatstart20 FBK_Z_Flatstart20 MFC_E_Z_Init20 MFC_E_D_Z_Init20 MFC_E_D_A_Z_Init20 MFC_E_D_A_Z_Flatstart20 MFC_E_D_Z_Flatstart20 MFC_E_Z_Flatstart20
    do
      for i in $(seq 2 2 20)
        hmm=hmm${i}4
        filename=decode-mono-$hmm
        if [$option = "GRAMMARSCALE" -o $option = "GRAMMARSCALE" ]; then
          for optvalue in $(seq 0 0.1 2)
          do
            ../tools/steps/step-decode -$option $optvalue $PWD/$file/mono $hmm $file/$option/$filename
            echo $file $filename -$option $optvalue >>text.txt
            grep -A2 -P 'SENT' $file/${option}${optvalue}/$filename/test/LOG >>text.txt
          done
        elif
            ../tools/steps/step-decode -$option $PWD/$file/mono $hmm $file/$option/$filename
            echo $file $filename -$option >>text.txt
	    grep -A2 -P 'SENT' $file/$option/$filename/test/LOG >>text.txt
	fi
	done 
     done 
done
	

